version: "3.8"

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"  # Backend läuft jetzt auf Port 5000
    environment:
      SQLITE_PATH: "/app/src/backend/worldskillsdata"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"  # Frontend läuft jetzt auf Port 3000
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true