# prodpipeline/Dockerfile.backend
FROM node:18

# Setze das Arbeitsverzeichnis auf den Ordner, in dem sich der Backend-Code befindet
WORKDIR /WorldSkillsTimeManager

# Installiere Abhängigkeiten
COPY ../src/backend/package*.json ./
RUN npm install && npm install -g nodemon

# Kopiere den Backend-Code in das Arbeitsverzeichnis
COPY ../src/backend .

# Setze die SQLite-Pfad-Umgebungsvariable
ENV SQLITE_PATH=/WorldSkillsTimeManager/src/backend/worldskillsdata

# Starte den Backend-Server
CMD ["nodemon", "run", "server.js"]
