version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: prodpipeline/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      SQLITE_PATH: "/WorldSkillsTimeManager/src/backend/worldskillsdata"
    volumes:
      - ../src/backend:/WorldSkillsTimeManager/src/backend
      - sqlite-data:/WorldSkillsTimeManager/src/backend/worldskillsdata
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ..
      dockerfile: prodpipeline/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000
    stdin_open: true
    tty: true

volumes:
  sqlite-data: